### ISSUE TITLE
Show modal dialog with React/Vue Component Rendering

### ISSUE THREAD

**Issue by pxwee5** [stripe-samples/payment-form-modal#6]
The examples here opens a modal that exists forever in the DOM. 

Can you show an example where the dialog gets removed from the DOM using React/Vue ? 

From my experience, `iframe` needs to reload when that happens, causing flash of no input whenever a dialog is opened, because the iframe will need to load the page containing the input field again.

**Comment by suz-stripe** [comment]
hey @pxwee5,

Thanks for opening this issue. 

How soon do you need to open the modal after the React/Vue route (if you use client side routing) has mounted? I ask this with regards to the iframe issue you mention - could you possibly include the modal in your parent / route component when it renders, but use a dynamically applied CSS class to hide it in a similar way to this example? If the user is only triggering this payment modal some time after the UI has mounted, then this strategy can load the iframe and modal functionality in advance of them opening the modal. Toggling the CSS class hiding the modal at the time the user triggers it via React/Vue should be possible.

Let me know if there are specific complications in your application as to why this approach wouldn't work.

Thanks!

**Comment by thorsten-stripe** [comment]
Closing due to staleness.
